---

- name: save new password hash to file
  ansible.builtin.copy:
    content: "{{ greenbone_admin_password | hash('sha256') }}"
    dest: "{{ greenbone_directory_work }}/greenbone_admin_password.hash"
    owner: "root"
    group: "root"
    mode: "0640"
  no_log: "{{ not disable_no_log | default(false) }}"
  notify: create admin credentials
